# Generated by Django 5.0.1 on 2024-04-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('engineering', 'Engineering')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=''),
        ),
    ]
