# Generated by Django 5.0.1 on 2024-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notice',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
