# Generated by Django 5.0.1 on 2024-04-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_notice_department_notice_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='department',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='semester',
        ),
    ]
