# Generated by Django 5.0.1 on 2024-01-13 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_alter_noticeboard_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
