# Generated by Django 5.0.1 on 2024-01-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_alter_noticeboard_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeboard',
            name='user',
        ),
    ]
